20-06-30 21:06-ERROR-division by zero
Traceback (most recent call last):
  File "C:/Users/27932/API_AUTO/tools/print_log.py", line 45, in <module>
    a = 1/0
ZeroDivisionError: division by zero
division by zero
Traceback (most recent call last):
  File "C:/Users/27932/API_AUTO/tools/print_log.py", line 45, in <module>
    a = 1/0
ZeroDivisionError: division by zero
